import { StyleSheet } from "react-native";
import { palette } from "./constants";

export const styles = StyleSheet.create({
  appRoot: {
    flex: 1,
    backgroundColor: palette.background,
  },
  publicContent: {
    flexGrow: 1,
    paddingBottom: 28,
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: palette.backgroundSoft,
  },
  landingTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  logoRow: {
    alignItems: "center",
    flexDirection: "row",
    marginVertical: -4,
  },
  logoImage: {
    height: 104,
    width: 268,
  },
  logoMark: {
    alignItems: "center",
    backgroundColor: palette.green,
    borderRadius: 18,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  logoText: {
    color: palette.text,
    fontSize: 27,
    letterSpacing: -1,
  },
  loginLink: {
    color: palette.muted,
    fontSize: 16,
  },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,53,63,0.12)",
    borderColor: "rgba(255,53,63,0.26)",
    borderWidth: 1,
    marginTop: 4,
  },
  badgeText: {
    color: palette.green,
  },
  heroTitle: {
    color: palette.text,
    fontSize: 56,
    letterSpacing: -2.4,
    lineHeight: 68,
    marginTop: 28,
  },
  heroTitleAccent: {
    color: palette.green2,
  },
  heroSubtitle: {
    color: palette.muted,
    fontSize: 22,
    lineHeight: 34,
    marginTop: 24,
  },
  featureList: {
    gap: 14,
    marginTop: 42,
  },
  featureCard: {
    alignItems: "center",
    backgroundColor: "rgba(26,15,16,0.84)",
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 16,
    minHeight: 66,
    paddingHorizontal: 20,
  },
  featureText: {
    color: palette.text,
    flex: 1,
    fontSize: 17,
  },
  publicActions: {
    gap: 16,
    marginTop: 34,
  },
  primaryButton: {
    borderRadius: 13,
  },
  primaryButtonContent: {
    flexDirection: "row-reverse",
    height: 58,
  },
  primaryButtonLabel: {
    color: palette.onAccent,
    fontSize: 17,
  },
  secondaryButton: {
    borderRadius: 13,
  },
  secondaryButtonContent: {
    height: 58,
  },
  authContent: {
    flexGrow: 1,
    paddingBottom: 34,
    paddingHorizontal: 16,
    paddingTop: 12,
    backgroundColor: palette.backgroundSoft,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: "rgba(31,21,22,0.84)",
    borderRadius: 24,
    height: 48,
    justifyContent: "center",
    marginBottom: 20,
    width: 48,
  },
  authTitle: {
    color: palette.text,
    fontSize: 42,
    letterSpacing: -1.7,
    marginTop: 22,
  },
  authSubtitle: {
    color: palette.muted,
    fontSize: 20,
    marginTop: 12,
  },
  authForm: {
    gap: 18,
    marginTop: 34,
    marginBottom: 28,
  },
  inputBlock: {
    gap: 10,
  },
  inputLabel: {
    color: palette.text,
    fontSize: 16,
  },
  textInput: {
    backgroundColor: palette.card,
    minHeight: 58,
  },
  inputHint: {
    color: palette.muted,
    fontSize: 14,
    marginTop: -10,
  },
  forgotPassword: {
    alignItems: "flex-end",
  },
  greenText: {
    color: palette.green,
  },
  courierSignupButton: {
    borderRadius: 13,
    marginTop: 16,
  },
  courierSignupContent: {
    height: 56,
  },
  demoRoles: {
    flexDirection: "row",
    gap: 10,
    marginTop: 30,
  },
  demoRoleButton: {
    alignItems: "center",
    backgroundColor: palette.cardSoft,
    borderRadius: 18,
    flex: 1,
    paddingVertical: 13,
  },
  demoRoleText: {
    color: palette.text,
  },
  demoText: {
    color: palette.muted,
    fontSize: 14,
    marginTop: 18,
    textAlign: "center",
  },
  authSwitch: {
    alignItems: "center",
    marginTop: 28,
  },
  authSwitchText: {
    color: palette.muted,
    fontSize: 16,
  },
  feedbackWrap: {
    paddingHorizontal: 20,
    paddingTop: 8,
    zIndex: 20,
  },
  feedback: {
    borderRadius: 16,
  },
  feedbackError: {
    backgroundColor: "#44181d",
  },
  feedbackSuccess: {
    backgroundColor: "#173823",
  },
  feedbackText: {
    color: palette.text,
  },
  screenContent: {
    flexGrow: 1,
    paddingBottom: 118,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  homeHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  homeAddressTrigger: {
    flex: 1,
    marginRight: 12,
  },
  mutedSmall: {
    color: palette.muted,
    fontSize: 14,
  },
  addressRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
    marginTop: 4,
  },
  addressText: {
    color: palette.text,
    flexShrink: 1,
    fontSize: 18,
  },
  addressCaption: {
    color: palette.muted,
    fontSize: 13,
    marginTop: 4,
  },
  homeAddressSelector: {
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    marginTop: 12,
    padding: 14,
  },
  homeAddressOption: {
    alignItems: "center",
    backgroundColor: palette.cardSoft,
    borderColor: palette.border,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    minHeight: 84,
    padding: 14,
  },
  homeAddressOptionActive: {
    borderColor: palette.green,
  },
  homeAddressOptionInfo: {
    flex: 1,
    minWidth: 0,
  },
  homeAddressOptionTitle: {
    color: palette.text,
    fontSize: 16,
  },
  homeAddressOptionText: {
    color: palette.text,
    fontSize: 14,
    marginTop: 4,
  },
  homeAddressOptionSubtext: {
    color: palette.muted,
    fontSize: 13,
    marginTop: 4,
  },
  homeAddressEmpty: {
    backgroundColor: palette.cardSoft,
    borderRadius: 16,
    padding: 14,
  },
  homeAddressEmptyTitle: {
    color: palette.text,
    fontSize: 15,
  },
  homeAddressEmptyText: {
    color: palette.muted,
    fontSize: 13,
    marginTop: 6,
  },
  notificationButton: {
    alignItems: "center",
    backgroundColor: palette.cardSoft,
    borderRadius: 25,
    height: 50,
    justifyContent: "center",
    width: 50,
  },
  notificationDot: {
    backgroundColor: palette.green,
    borderRadius: 7,
    height: 14,
    position: "absolute",
    right: 8,
    top: 8,
    width: 14,
  },
  searchBox: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderRadius: 18,
    flexDirection: "row",
    gap: 14,
    height: 58,
    marginTop: 28,
    paddingHorizontal: 18,
  },
  searchInput: {
    backgroundColor: "transparent",
    flex: 1,
    height: 56,
  },
  searchInputContent: {
    color: palette.text,
    fontSize: 18,
    paddingLeft: 0,
  },
  promoCard: {
    alignItems: "center",
    backgroundColor: palette.green,
    borderRadius: 28,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 22,
    overflow: "hidden",
    padding: 26,
  },
  promoBrandImage: {
    height: 56,
    opacity: 0.9,
    width: 146,
  },
  promoKicker: {
    color: palette.onAccent,
    fontSize: 13,
    letterSpacing: 2,
  },
  promoTitle: {
    color: palette.onAccent,
    fontSize: 28,
    marginTop: 8,
  },
  promoSubtitle: {
    color: "#ffd6da",
    fontSize: 18,
    marginTop: 8,
  },
  categoryList: {
    gap: 12,
    marginTop: 30,
    paddingRight: 20,
  },
  categoryPill: {
    alignItems: "center",
    backgroundColor: palette.cardSoft,
    borderColor: palette.border,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    minHeight: 54,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  categoryPillActive: {
    backgroundColor: palette.green,
    borderColor: palette.green,
  },
  categoryPillImage: {
    height: 22,
    width: 22,
  },
  categoryText: {
    color: palette.muted,
    fontSize: 15,
  },
  categoryTextActive: {
    color: palette.onAccent,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 36,
  },
  sectionTitle: {
    color: palette.text,
    fontSize: 24,
    letterSpacing: -0.7,
  },
  mutedText: {
    color: palette.muted,
    fontSize: 15,
  },
  productGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginTop: 16,
  },
  productCardWrap: {
    width: "48%",
  },
  productCard: {
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    overflow: "hidden",
    padding: 12,
    width: "100%",
  },
  productImage: {
    backgroundColor: palette.cardSoft,
    borderRadius: 14,
    height: 148,
    width: "100%",
  },
  discountBadge: {
    backgroundColor: palette.green,
    borderRadius: 13,
    left: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
    position: "absolute",
    top: 12,
  },
  discountText: {
    color: palette.onAccent,
    fontSize: 12,
  },
  soldOutBadge: {
    backgroundColor: palette.danger,
    borderRadius: 13,
    paddingHorizontal: 10,
    paddingVertical: 6,
    position: "absolute",
    right: 12,
    top: 12,
  },
  soldOutText: {
    color: palette.text,
    fontSize: 12,
  },
  productName: {
    color: palette.text,
    fontSize: 18,
    marginTop: 14,
    minHeight: 44,
  },
  oldPrice: {
    color: palette.muted,
    fontSize: 13,
    marginTop: 8,
    textDecorationLine: "line-through",
  },
  priceRow: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: 6,
  },
  productPrice: {
    color: palette.green,
    fontSize: 18,
  },
  unitText: {
    color: palette.muted,
    flex: 1,
    fontSize: 12,
    marginLeft: 3,
  },
  addButton: {
    alignItems: "center",
    backgroundColor: palette.green,
    borderRadius: 20,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  addButtonDisabled: {
    backgroundColor: "rgba(255,53,63,0.12)",
  },
  floatingCart: {
    alignItems: "center",
    backgroundColor: palette.green,
    borderRadius: 18,
    bottom: 92,
    flexDirection: "row",
    gap: 10,
    left: 20,
    paddingHorizontal: 18,
    paddingVertical: 14,
    position: "absolute",
    right: 20,
  },
  floatingCartText: {
    color: palette.onAccent,
    flex: 1,
  },
  screenTitle: {
    color: palette.text,
    fontSize: 36,
    letterSpacing: -1,
  },
  screenTitleCompact: {
    color: palette.text,
    fontSize: 24,
  },
  cartList: {
    gap: 16,
    marginTop: 20,
  },
  cartItem: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 15,
    padding: 14,
  },
  cartImage: {
    borderRadius: 12,
    height: 96,
    width: 96,
  },
  cartInfo: {
    flex: 1,
  },
  cartName: {
    color: palette.text,
    fontSize: 18,
  },
  cartPrice: {
    color: palette.muted,
    fontSize: 14,
    marginTop: 4,
  },
  quantityRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 14,
    marginTop: 13,
  },
  quantityButton: {
    alignItems: "center",
    backgroundColor: "#160f10",
    borderRadius: 18,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  quantityText: {
    color: palette.text,
    fontSize: 18,
  },
  cartTrashButton: {
    alignItems: "center",
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  summaryCard: {
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: 18,
    marginTop: 28,
    padding: 20,
  },
  summaryRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  summaryLabel: {
    color: palette.muted,
    fontSize: 17,
  },
  summaryValue: {
    color: palette.text,
    fontSize: 17,
  },
  summaryDivider: {
    backgroundColor: palette.border,
    height: 1,
  },
  summaryLarge: {
    color: palette.text,
    fontSize: 23,
  },
  summaryLargeValue: {
    color: palette.green,
    fontSize: 23,
  },
  emptyState: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 20,
    borderWidth: 1,
    gap: 10,
    marginTop: 28,
    padding: 28,
  },
  emptyTitle: {
    color: palette.text,
    fontSize: 19,
  },
  emptyText: {
    color: palette.muted,
    fontSize: 15,
    textAlign: "center",
  },
  productDetailRoot: {
    flex: 1,
    backgroundColor: palette.background,
  },
  productDetailContent: {
    flexGrow: 1,
    paddingBottom: 116,
  },
  productHero: {
    backgroundColor: palette.backgroundSoft,
    height: 268,
  },
  productHeroImage: {
    height: "100%",
    width: "100%",
  },
  detailBackButton: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderRadius: 24,
    height: 48,
    justifyContent: "center",
    left: 20,
    position: "absolute",
    top: 18,
    width: 48,
  },
  productDetailSheet: {
    backgroundColor: palette.background,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: -28,
    paddingHorizontal: 22,
    paddingTop: 36,
  },
  detailCategory: {
    color: palette.green,
    fontSize: 14,
    letterSpacing: 1,
    marginBottom: 12,
  },
  detailTitle: {
    color: palette.text,
    fontSize: 36,
    letterSpacing: -1,
  },
  detailPriceRow: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 8,
    marginTop: 18,
  },
  detailPrice: {
    color: palette.green,
    fontSize: 34,
    letterSpacing: -0.8,
  },
  detailUnit: {
    color: palette.muted,
    fontSize: 18,
    marginBottom: 5,
  },
  detailSectionTitle: {
    color: palette.text,
    fontSize: 20,
    marginTop: 34,
  },
  detailDescription: {
    color: palette.muted,
    fontSize: 17,
    lineHeight: 25,
    marginTop: 14,
  },
  stockCard: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 30,
    padding: 20,
  },
  stockLabel: {
    color: palette.muted,
    fontSize: 16,
  },
  stockValue: {
    color: palette.green,
    fontSize: 16,
  },
  productDetailFooter: {
    alignItems: "center",
    backgroundColor: "rgba(20,12,15,0.96)",
    borderTopColor: palette.border,
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: "row",
    gap: 14,
    left: 0,
    paddingBottom: 18,
    paddingHorizontal: 22,
    paddingTop: 16,
    position: "absolute",
    right: 0,
  },
  detailQuantityControl: {
    alignItems: "center",
    backgroundColor: palette.cardSoft,
    borderRadius: 24,
    flexDirection: "row",
    height: 58,
    justifyContent: "space-between",
    paddingHorizontal: 8,
    width: 168,
  },
  detailQuantityButton: {
    alignItems: "center",
    backgroundColor: "#160f10",
    borderRadius: 22,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  detailQuantityText: {
    color: palette.text,
    fontSize: 20,
  },
  detailAddButton: {
    borderRadius: 16,
    flex: 1,
  },
  detailAddButtonContent: {
    height: 58,
  },
  checkoutRoot: {
    flex: 1,
    backgroundColor: palette.backgroundSoft,
  },
  checkoutContent: {
    flexGrow: 1,
    paddingBottom: 122,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  checkoutHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 14,
    marginBottom: 28,
  },
  checkoutSectionLabel: {
    color: palette.muted,
    fontSize: 15,
    letterSpacing: 2,
    marginBottom: 16,
    marginTop: 8,
  },
  deliveryOptions: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 30,
  },
  checkoutOption: {
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 17,
    borderWidth: 1,
    flex: 1,
    minHeight: 122,
    padding: 20,
  },
  checkoutOptionActive: {
    backgroundColor: "rgba(255,53,63,0.12)",
    borderColor: palette.green,
  },
  checkoutOptionTitle: {
    color: palette.text,
    fontSize: 21,
    marginTop: 18,
  },
  checkoutOptionSubtitle: {
    color: palette.muted,
    fontSize: 14,
    marginTop: 4,
  },
  addressCard: {
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 30,
    padding: 20,
  },
  addressCardTitle: {
    color: palette.text,
    fontSize: 20,
  },
  addressCardText: {
    color: palette.muted,
    fontSize: 17,
    marginTop: 6,
  },
  addressCardSubtext: {
    color: palette.muted,
    fontSize: 14,
    marginTop: 8,
  },
  addressPrimaryButton: {
    borderRadius: 16,
    marginTop: 18,
  },
  addressPrimaryButtonContent: {
    height: 54,
  },
  addressEditorCard: {
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 22,
    borderWidth: 1,
    gap: 18,
    marginTop: 18,
    padding: 18,
  },
  addressEditorTitle: {
    color: palette.text,
    fontSize: 22,
  },
  addressFormGrid: {
    gap: 14,
  },
  addressFormRow: {
    flexDirection: "row",
    gap: 12,
  },
  addressFormSmallField: {
    width: 92,
  },
  addressEditorActions: {
    flexDirection: "row",
    gap: 12,
  },
  addressSecondaryButton: {
    borderRadius: 14,
    flex: 1,
  },
  addressSaveButton: {
    borderRadius: 14,
    flex: 1,
  },
  addressSecondaryButtonContent: {
    height: 50,
  },
  addressList: {
    gap: 14,
    marginTop: 22,
  },
  userAddressCard: {
    backgroundColor: palette.card,
    borderRadius: 20,
    borderWidth: 1,
    padding: 18,
  },
  userAddressCardActive: {
    borderColor: palette.green,
    opacity: 1,
  },
  userAddressCardInactive: {
    borderColor: palette.border,
    opacity: 0.6,
  },
  addressCardHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
  },
  addressCardInfo: {
    flex: 1,
    minWidth: 0,
  },
  lastUsedBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,53,63,0.16)",
    borderRadius: 14,
    flexShrink: 0,
    maxWidth: 132,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  lastUsedBadgeText: {
    color: palette.green,
    fontSize: 12,
    textAlign: "center",
  },
  addressZipText: {
    color: palette.text,
    fontSize: 13,
    marginTop: 12,
  },
  addressActionRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 4,
    marginTop: 14,
  },
  paymentList: {
    gap: 12,
  },
  paymentOption: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 16,
    minHeight: 88,
    padding: 18,
  },
  paymentOptionActive: {
    backgroundColor: "rgba(255,53,63,0.12)",
    borderColor: palette.green,
  },
  paymentIcon: {
    alignItems: "center",
    backgroundColor: palette.cardSoft,
    borderRadius: 14,
    height: 50,
    justifyContent: "center",
    width: 50,
  },
  paymentIconActive: {
    backgroundColor: palette.green,
  },
  paymentTitle: {
    color: palette.text,
    fontSize: 20,
  },
  paymentSubtitle: {
    color: palette.muted,
    fontSize: 14,
    marginTop: 4,
  },
  checkoutFooter: {
    alignItems: "center",
    backgroundColor: "rgba(20,12,15,0.96)",
    borderTopColor: palette.border,
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: "row",
    gap: 16,
    left: 0,
    paddingBottom: 18,
    paddingHorizontal: 20,
    paddingTop: 16,
    position: "absolute",
    right: 0,
  },
  checkoutTotalLabel: {
    color: palette.muted,
    fontSize: 14,
  },
  checkoutTotal: {
    color: palette.green,
    fontSize: 23,
    marginTop: 4,
  },
  checkoutButton: {
    borderRadius: 14,
    flex: 1,
  },
  checkoutButtonContent: {
    height: 58,
  },
  orderCard: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
    minHeight: 170,
    padding: 20,
  },
  orderMeta: {
    color: palette.muted,
    fontSize: 15,
  },
  orderItems: {
    color: palette.text,
    fontSize: 22,
    marginTop: 10,
  },
  orderTotal: {
    color: palette.green,
    fontSize: 18,
    marginTop: 13,
  },
  statusBadge: {
    alignSelf: "flex-start",
    borderRadius: 18,
    marginTop: 18,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  statusBadge_success: {
    backgroundColor: "#153824",
  },
  statusBadge_warning: {
    backgroundColor: "#3f2d0a",
  },
  statusBadge_danger: {
    backgroundColor: "#421719",
  },
  statusBadgeText: {
    fontSize: 13,
  },
  statusBadgeText_success: {
    color: palette.success,
  },
  statusBadgeText_warning: {
    color: palette.warning,
  },
  statusBadgeText_danger: {
    color: palette.danger,
  },
  profileCard: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 22,
    marginTop: 22,
    padding: 24,
  },
  avatar: {
    alignItems: "center",
    backgroundColor: palette.green,
    borderRadius: 38,
    height: 76,
    justifyContent: "center",
    width: 76,
  },
  avatarText: {
    color: palette.onAccent,
    fontSize: 26,
  },
  profileName: {
    color: palette.text,
    fontSize: 21,
  },
  profileEmail: {
    color: palette.muted,
    fontSize: 15,
    marginTop: 5,
  },
  roleBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#4a1c20",
    borderRadius: 12,
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  roleBadgeText: {
    color: palette.green,
    fontSize: 12,
  },
  profileAction: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 18,
    marginTop: 12,
    minHeight: 86,
    paddingHorizontal: 18,
  },
  profileActionActive: {
    borderColor: palette.green,
  },
  profileActionIcon: {
    alignItems: "center",
    backgroundColor: palette.cardSoft,
    borderRadius: 12,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  profileActionText: {
    color: palette.text,
    flex: 1,
    fontSize: 20,
  },
  logoutAction: {
    borderColor: palette.border,
  },
  logoutIcon: {
    backgroundColor: "#3b191c",
  },
  logoutText: {
    color: palette.danger,
    flex: 1,
    fontSize: 20,
  },
  trackHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 18,
  },
  backCircle: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderRadius: 26,
    height: 52,
    justifyContent: "center",
    width: 52,
  },
  deliveryCodeCard: {
    alignItems: "center",
    backgroundColor: palette.green2,
    borderRadius: 24,
    marginTop: 28,
    padding: 28,
  },
  deliveryCodeLabel: {
    color: "#ffe6e8",
    fontSize: 13,
    letterSpacing: 3,
  },
  deliveryCode: {
    color: palette.onAccent,
    fontSize: 70,
    letterSpacing: 12,
    marginTop: 8,
  },
  deliveryCodeHint: {
    color: "#ffe6e8",
    fontSize: 16,
  },
  courierCard: {
    alignItems: "center",
    backgroundColor: palette.card,
    borderColor: palette.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 14,
    marginTop: 30,
    padding: 22,
  },
  courierAvatar: {
    alignItems: "center",
    backgroundColor: "#4a1c20",
    borderRadius: 30,
    height: 58,
    justifyContent: "center",
    width: 58,
  },
  courierPhoto: {
    borderRadius: 29,
    height: 58,
    width: 58,
  },
  courierAvatarText: {
    color: palette.onAccent,
    fontSize: 24,
  },
  courierName: {
    color: palette.text,
    fontSize: 20,
  },
  trackTitle: {
    color: palette.text,
    fontSize: 22,
    marginTop: 30,
  },
  timeline: {
    marginTop: 20,
  },
  timelineItem: {
    alignItems: "center",
    flexDirection: "row",
    gap: 18,
    marginBottom: 28,
  },
  timelineIcon: {
    alignItems: "center",
    backgroundColor: palette.cardSoft,
    borderRadius: 24,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  timelineIconCurrent: {
    backgroundColor: palette.green,
  },
  timelineIconDelivered: {
    backgroundColor: palette.success,
  },
  timelineLabel: {
    fontSize: 21,
  },
  timelineLabelCurrent: {
    color: palette.text,
  },
  timelineLabelDelivered: {
    color: palette.success,
  },
  timelineLabelMuted: {
    color: palette.muted,
  },
  timelineTime: {
    color: palette.muted,
    fontSize: 15,
    marginTop: 2,
  },
  bottomTabs: {
    alignItems: "center",
    backgroundColor: "rgba(30,20,20,0.98)",
    borderTopColor: palette.border,
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: "row",
    height: 78,
    justifyContent: "space-around",
    left: 0,
    position: "absolute",
    right: 0,
  },
  tabButton: {
    alignItems: "center",
    gap: 5,
  },
  tabLabel: {
    color: palette.muted,
    fontSize: 13,
  },
  tabLabelActive: {
    color: palette.green,
  },
  flex: {
    flex: 1,
  },
});
